#!/usr/local/bin/bash

# Pre compiles gcc for NodeOS

SOURCES=`pwd`/deps
TOOLS=`pwd`/tools

GCC_VERSION=4.7.3
echo Compiling GCC

GCC_URL=http://ftpmirror.gnu.org/gcc/gcc-4.7.3/gcc-4.7.3.tar.gz
echo $GCC_URL
SRC_DIR=$SOURCES/gcc

mkdir -p $SRC_DIR
curl -L $GCC_URL | tar xzf - -C $SRC_DIR --strip-components=1

